version: "3.9"
services:
  profinity:
    # image: "prohelion/profinity-console:develop"
    build: .
    ports:
      - '5000:5000'
      - '15000:15000'
    volumes:
      - ./Profinity:/root/Prohelion/Profinity