Version: 1
ActiveProfile: /root/Prohelion/Profinity/Profiles/Default.pprof
ClientId: 8c4acb6b-7cc8-4322-bf45-b61a3e99e044
Options:
  BMSCalibration: false
  CMUCalibration: false
  WebServer:
    InternalUrls: http://profinity:15000
    Urls: http://profinity:5000
    HttpsRedirect: false
    WebSite:
      Enabled: true
    RestAPI:
      Enabled: true
      Swagger: true
AppSettings:
  MaxRetainedCanPackets: 1000
  Logs:
    LogLevel: Trace
    RollsizeMB: 1
    RetainedLogs: 10
